### ISSUE TITLE
[Question] What if two or more resource packs try to replace the same file?

### ISSUE THREAD

**Issue by rishubil** [MajsoulPlus/majsoul-plus#102]
I am currently making a [resource pack to play Majsoul in Korean](https://github.com/yf-dev/majsoul-plus-korean).
Its main purpose is to provide players with a translation that is purely faithful to the original text of the game.

However, since most Koreans are not familiar with mahjong games, it is difficult to learn and play mahjong with only the tutorials provided in the game.
As a result, I planned to create additional resource packs to further refine the content of the Majsoul tutorial.

In this case, "Majsoul Korean Resource Pack" and "Detailed Tutorial Resource Pack" will modify the same file. Also, the "Detailed Tutorial Resource Pack" file should be applied first.

So I want to know if there is a way to make sure that two or more resource packs are prioritized when trying to replace the same file.

**Comment by iamapig120** [comment]
As @Yesterday17 said, the later you enable the resource pack, the higher priority is.

**Comment by Yesterday17** [comment]
The way Majsoul Plus applies resource packs(and resources in extensions) is to **rewrite** the path of a resource file ruled in a key-value Map(usually called `resversion.json`). And resource packs have higher priority than extensions.

**Comment by rishubil** [comment]
I checked what you said. Thanks for the help.
