### ISSUE TITLE
[BUG] Сan't log in through Google account

### ISSUE THREAD

**Issue by alexhoujuu** [MajsoulPlus/majsoul-plus#107]
**Bug 描述**
When I try to log in through my Google account, it displays this message. I tried changing the settings and turning off the check for unsafe apps on my account, but that didn't fix the issues.

**截图**
![1515151](https://user-images.githubusercontent.com/70319906/91438497-1c7c9b00-e874-11ea-928a-b4a6d412124b.png)
**客户端信息:**
 - 操作系统: Windows 10
 - 系统架构 x64
 - 版本号 v2.0.0

**Comment by Yesterday17** [comment]
Seems google oauth checks browser User-Agent...

**Comment by alexhoujuu** [comment]
> Seems google oauth checks browser User-Agent...
> 
> https://stackoverflow.com/questions/59685927/electron-application-using-google-oauth-this-browser-or-app-may-not-be-secure

Is it possible to avoid this check?

**Comment by alexhoujuu** [comment]
Found a workaround. You need to go through a browser and bind your account to a new mail (settings > others). After that, you will be able to log into the client through a new email.
