### ISSUE TITLE
[BUG] can't login with google account

### ISSUE THREAD

**Issue by tjtjdnjswhd** [MajsoulPlus/majsoul-plus#110]
**Bug 描述**
I removed %appData%Majsoul Plus becauseof [this problem](https://github.com/MajsoulPlus/majsoul-plus/issues/101) and reinstall by Majsoul_Plus-2.0.1-win32-Setup.exe
I try login with google. but it show can't login, this browser or app may not safe

**如何重现**
1. click google login
2. type google Id and click next
3. google show 'can't login' browser or app may not safe

**客户端信息 (请完善以下信息):**
 - 操作系统: window 10
 - 系统架构 x64
 - 版本号 2.0.1

**备注**
google say if using supporting browser but can't login, set javaScript option use

**Comment by Yesterday17** [comment]
I believe it's related to #107

**Comment by tjtjdnjswhd** [comment]
Oh, I missed that. thanks
