### ISSUE TITLE
[BUG] win10开启ipv6会导致无法进入游戏

### ISSUE THREAD

**Issue by jmwangde3** [MajsoulPlus/majsoul-plus#144]
开始能正常使用,中间要登录日服用加速器加速了一次游戏,之后不管什么服务器都无法进入游戏,表现为黑屏,或者在登陆界面几个服务器全部无法连接.恢复系统网络设置,删除游戏(包括appdata里的所有内容)重装都无效,最后系统里关掉ipv6解决了

**客户端信息 (请完善以下信息):**
 - 操作系统: win10
 - 系统架构 x64
 - 版本号 2.00,2.01

**Comment by iamapig120** [comment]
非常感谢您的来信该邮件已成功接收至手柄的邮箱您的建议及意见会经过阅读后成为优秀的参考选项To customers:I passed the postgraduate exam! Everything will return to normal in a few days!

**Comment by jmwangde3** [comment]
玩着掉线了重新进又进不去了,抓包看到连接的ip地址,本地和代理ping都ping不通
