### ISSUE TITLE
[BUG] 插件所在文件夹被资源管理器打开时，卸载插件文件夹会进入无法访问的状态

### ISSUE THREAD

**Issue by kangzq0530** [MajsoulPlus/majsoul-plus#21]
**Bug 描述**
如题

**如何重现**
以下为重现步骤：
1. 打开某插件文件夹，如/majsoulplus/resources/app/execute/xxx
2. 点击 主界面删除该插件

**预期行为**
一段清楚且简练的描述说明您预期的行为

**截图**
如果您方便的话，可以添加屏幕截图来方便描述您的问题
![image](https://user-images.githubusercontent.com/32447420/52254464-dafe6500-2948-11e9-9ae9-8b0d9f69769a.png)

**客户端信息 (请完善以下信息):**
OS win10x64 17134
 - 操作系统: [e.g. Windows] 
 - 系统架构 [e.g. ia32, x64]
 - 版本号 [e.g. v1.5.0]

**备注**
任何有关于这个Bug的其他信息

**Comment by iamapig120** [comment]
唔……似乎只有win上面会这样……

**Comment by molingyu** [comment]
@iamapig120  将文件夹删除改成调用系统命令如何？加个 os 的判断 然后调用对应的系统命令删除文件夹

**Comment by iamapig120** [comment]
> @iamapig120 将文件夹删除改成调用系统命令如何？加个 os 的判断 然后调用对应的系统命令删除文件夹

所以你的意思是重新造一个 fs 轮子？？？

**Comment by molingyu** [comment]
@iamapig120 请查看提交
