### ISSUE TITLE
[BUG] The latest release is broken on Ubuntu

### ISSUE THREAD

**Issue by purerosefallen** [MajsoulPlus/majsoul-plus#29]
**Bug Description**
When I use the latest release of the client `https://github.com/MajsoulPlus/majsoul-plus-client/releases/download/v1.10.6/Majsoul_Plus-linux-x64.zip`, it can't run.

**Step to Reproduce**
Download and unzip the latest archive, and `./Majsoul_Plus`.

**Expected Behavior**
It should run properly without crashing.

**Screenshot**

My bash acts as follows.
```
nanahira@nanahira-another:~/test/majsoulp/Majsoul_Plus-linux-x64$ ./Majsoul_Plus 
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
ome/nanahira/test/majsoulp/Majsoul_Plus-linux-x64/Majsoul_Plus: ../../src/xcb_io.c:259：poll_for_event: 假设 ‘!xcb_xlib_threads_sequence_lost’ 失败。
已放弃 (核心已转储)
nanahira@nanahira-another:~/test/majsoulp/Majsoul_Plus-linux-x64$ 
```

**OS information**
 - Ubuntu
 - x64
 - 18.04.2 LTS

**Comment by iamapig120** [comment]
Got it
But now I have no ubuuntu OS to test...
Maybe it will be fixed later
sry~

**Comment by molingyu** [comment]
@purerosefallen hi, Can other Electron apps work on your computer？

**Comment by purerosefallen** [comment]
Other electron apps worked fine. @molingyu

**Comment by kangzq0530** [comment]
i got the same problem.
OS:Ubuntu 18.04.2 x64
log:
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
ome/ethan/my/games/MajsoulPlus/Majsoul_Plus: ../../src/xcb_io.c:165：dequeue_pending_request: 假设 ‘!xcb_xlib_unknown_req_in_deq’ 失败。
已放弃 (核心已转储)

**Comment by molingyu** [comment]
@purerosefallen electron/electron#12329

> Note:
RPI3B, Debian Stretch, within docker container (i.e. no OpenGL), [electron-quick-start](https://github.com/electron/electron-quick-start) with electron@2.0.5 works as explained [here](https://github.com/electron/electron/issues/12937#issuecomment-389421787) by setting `app.disableHardwareAcceleration();` at [this](https://github.com/electron/electron-quick-start/blob/dc1585b235a00bb6842ee2fd0e56fd94fdc1123e/main.js#L3) location.
>
> Or run just run `electron --disable-gpu` as described [here](https://peter.sh/experiments/chromium-command-line-switches/).
>
> Alternatively, installing libgl1-mesa-dri (apt install --no-install-recommends libgl1-mesa-dri) also works, without any of the above flags.

我们计划在新版本将 ` in-process-gpu` 默认设置为禁用。如果是 Linux 系统希望能启用该设置，则 `install --no-install-recommends libgl1-mesa-dri` 后再启用。
