### ISSUE TITLE
Fails to build on Manjaro

### ISSUE THREAD

**Issue by arsdragonfly** [MajsoulPlus/majsoul-plus#30]
log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.7.0
3 info using node@v11.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle majsoul-plus-client@1.10.7-alpha.1~prestart: majsoul-plus-client@1.10.7-alpha.1
6 info lifecycle majsoul-plus-client@1.10.7-alpha.1~start: majsoul-plus-client@1.10.7-alpha.1
7 verbose lifecycle majsoul-plus-client@1.10.7-alpha.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle majsoul-plus-client@1.10.7-alpha.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/arsdragonfly/majsoul-plus-client/node_modules/.bin:/home/arsdragonfly/bin:/usr/local/bin:/home/arsdragonfly/.local/bin:/home/arsdragonfly/.cabal/bin:/home/arsdragonfly/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/bin:/home/arsdragonfly/.cabal/bin/:/home/arsdragonfly/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/bin:/home/arsdragonfly/.cabal/bin/:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle majsoul-plus-client@1.10.7-alpha.1~start: CWD: /home/arsdragonfly/majsoul-plus-client
10 silly lifecycle majsoul-plus-client@1.10.7-alpha.1~start: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=development electron . --enable_logging' ]
11 silly lifecycle majsoul-plus-client@1.10.7-alpha.1~start: Returned: code: 1  signal: null
12 info lifecycle majsoul-plus-client@1.10.7-alpha.1~start: Failed to exec start script
13 verbose stack Error: majsoul-plus-client@1.10.7-alpha.1 start: `cross-env NODE_ENV=development electron . --enable_logging`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid majsoul-plus-client@1.10.7-alpha.1
15 verbose cwd /home/arsdragonfly/majsoul-plus-client
16 verbose Linux 4.20.3-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v11.6.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error majsoul-plus-client@1.10.7-alpha.1 start: `cross-env NODE_ENV=development electron . --enable_logging`
22 error Exit status 1
23 error Failed at the majsoul-plus-client@1.10.7-alpha.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by iamapig120** [comment]
Got it,
we will try to repeat it.
If you fixed it anytime,
welcome to create pull request

**Comment by iamapig120** [comment]
Could you try it again in the latest version?
Maybe fixed.

**Comment by iamapig120** [comment]
I tried it again
And... Build successed

**Comment by arsdragonfly** [comment]
Fixed on latest master
