### ISSUE TITLE
[feature request] 添加 macOS Dark Mode 支持

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [MajsoulPlus/majsoul-plus#31]
**您是在使用中遇到了什么问题导致的您提交功能建议么？如果是，请描述您遇到的问题**
不支持 macOS 下的 Dark Mode

**描述您希望的解决方案**
能够在 Dark Mode 下对颜色进行适配

**描述您希望的备选方案**
```NULL```

**备注**
macOS Dark Mode 下雀魂 Plus 的窗口边框：
<img width="1303" alt="cleanshot 2019-02-09 at 16 02 10 2x" src="https://user-images.githubusercontent.com/25654046/52518333-2afc6500-2c84-11e9-8fec-9e5791f69c0a.png">

macOS Dark Mode 下系统原生应用的窗口边框：
<img width="1198" alt="cleanshot 2019-02-09 at 16 04 22 2x" src="https://user-images.githubusercontent.com/25654046/52518342-6303a800-2c84-11e9-93c5-dc006a5037a7.png">

**Comment by iamapig120** [comment]
已收到，并着手实现
由于手头没有macOS机器，可能会优先实现windows暗主题
