### ISSUE TITLE
[feature request] 希望增加一个较为完整的模组制作教程

### ISSUE THREAD

**Issue by PonyEternalBlue** [MajsoulPlus/majsoul-plus#36]
**您是在使用中遇到了什么问题导致的您提交功能建议么？如果是，请描述您遇到的问题**
创建自定义模组对于没有编程基础的小白极不友好......

**描述您希望的解决方案**
在wiki或程序里建立一个可供参考的模组制作教程

**描述您希望的备选方案**
可以通过添加一个更为全面的示例模组（例如替换掉游戏里的所有资源文件）来让用户可以通过直接向files文件夹内添加/修改文件，并在程序内进行简单的修改，实现自定义模组
如果能增加一个模组编辑的GUI就更好了

**备注**
教程中可以包含资源文件路径列表

**Comment by 2938137849** [comment]
有心,不过不能直接push,fork也fork不到wiki的东西,无力

**Comment by molingyu** [comment]
https://github.com/MajsoulPlus/majsoul-plus-wiki

@2938137849 @PonyEternalBlue

**Comment by iamapig120** [comment]
https://github.com/MajsoulPlus/majsoul-plus/wiki
