### ISSUE TITLE
[feature request] 新的插件系统

### ISSUE THREAD

**Issue by molingyu** [MajsoulPlus/majsoul-plus#39]
## 关于重构新的插件系统
为支持线长插件库，需要对现有的插件系统做出更新和重构。

- [ ] 添加 `version` 等字段
- [ ] 添加插件的依赖系统
- [ ] 为新的插件系统的配置文件提供 schema

**Comment by molingyu** [comment]
#40
我完成了 `mod.json` 的 schema
为了方便用于依赖系统等，添加了全新的 `idName` 字段。`idName` 将比 `name` 更加严格，也更加符合计算机底层操作（比如全英文）。这个名称也将用于线上库的唯一 `id` 标识（mod/execute/tool 将共用同一个 id 池）。

**Comment by molingyu** [comment]
关于 语义化的版本比较，打算使用 [node-semver](https://github.com/npm/node-semver) 来处理
而关于插件是否符合规范，将使用 [jsonschema](https://github.com/tdegrunt/jsonschema) 来做验证

**Comment by iamapig120** [comment]
长期未跟进，暂时Close
