### ISSUE TITLE
网络正常的情况下QQ登陆黑屏

### ISSUE THREAD

**Issue by 1847bell** [MajsoulPlus/majsoul-plus#42]
在预览版及正式版中都存在的情况

使用QQ扫码登陆后会跳转为黑屏，无论是否关闭GPU加速。关闭所有插件也无法解决。

备注：
1. 网络正常，可以正常获取延迟
2. 网页版可以正常的打开

**Comment by iamapig120** [comment]
请问下是否有开启全局代理一类的代理工具
