### ISSUE TITLE
希望作者将包发布到aur上。

### ISSUE THREAD

**Issue by Kryptia** [MajsoulPlus/majsoul-plus#43]
希望作者将majsoulplus发布到aur源上，这样就可以方便的使用pacman管理包辣～

**Comment by iamapig120** [comment]
欢迎社区提交雀魂Plus到AUR源上，捂脸
（我所在的网络环境无法使用 git 协议的 git 仓库……而且不太了解 arch 平台……）
或许您也可以一起参与到 雀魂 Plus 项目当中，欢迎您的 PR

**Comment by BruceZhang1993** [comment]
https://aur.archlinux.org/packages/majsoul-plus    

你好，这里是 AUR & Arch Linux CN 打包~~狗~~者一只
已经使用源码打包到 AUR 欢迎试用，有打包错误直接在 AUR 评论即可

**Comment by iamapig120** [comment]
> https://aur.archlinux.org/packages/majsoul-plus
> 
> 你好，这里是 AUR & Arch Linux CN 打包狗者一只
> 已经使用源码打包到 AUR 欢迎试用，有打包错误直接在 AUR 评论即可

非常感谢！现已加入 README 豪华午餐（雾

**Comment by Kryptia** [comment]
> https://aur.archlinux.org/packages/majsoul-plus
> 
> 你好，这里是 AUR & Arch Linux CN 打包狗者一只
> 已经使用源码打包到 AUR 欢迎试用，有打包错误直接在 AUR 评论即可

感谢 @BruceZhang1993 ！
