### ISSUE TITLE
[BUG] 打开一次雀魂Plus v1.10.8-alpha.7 之后，所有版本PLUS均无法打开

### ISSUE THREAD

**Issue by ye602a** [MajsoulPlus/majsoul-plus#44]
**Bug 描述**
清晰和简练地介绍 BUG 内容

**如何重现**
打开一次雀魂Plus v1.10.8-alpha.7 之后，所有其他版本PLUS均无法打开

**预期行为**
之前使用的Plus v1.10.8-alpha.5 ，今天覆盖更新了alpha.7进入直接弹出错误提示，之后任何版本plus均无法打开，重启也是如此。

**截图**
![2019-03-03 153602](https://user-images.githubusercontent.com/48172733/53692406-4f061e80-3dca-11e9-8664-fa81f4cefd65.jpg)

**客户端信息 (请完善以下信息):**
 - 操作系统 windows10
 - 系统架构 x64
 - 版本号 1809

**Comment by kangzq0530** [comment]
进入%appdata% 删除雀p的文件夹即可

**Comment by iamapig120** [comment]
https://github.com/MajsoulPlus/majsoul-plus/commit/84047d1d302320f4b92e56d294d2dceacf993d99
已在这次 Release 修正，请等待稍晚些推送更新
