### ISSUE TITLE
[feature request] 关于静态资源文件缓存的建议

### ISSUE THREAD

**Issue by BruceZhang1993** [MajsoulPlus/majsoul-plus#46]
**您是在使用中遇到了什么问题导致的您提交功能建议么？如果是，请描述您遇到的问题**
运行环境：Arch Linux
尝试打包到 AUR 但运行时会尝试往 `应用安装位置/resources/app/static` 缓存静态文件，一般打包以后这个位置是不允许在普通用户权限下修改，例如 `/opt/majsoul-plus/resources/app/static`

**描述您希望的解决方案**
修改静态文件的缓存位置到用户主目录下的合适位置

**Comment by iamapig120** [comment]
唔……打包的话……这里如果不打包 asar 的话……应该是可以正常写入的……
具体不是很了解，捂脸
以后会尝试加入选项以手动指定缓存路径

**Comment by BruceZhang1993** [comment]
> 唔……打包的话……这里如果不打包 asar 的话……应该是可以正常写入的……
> 具体不是很了解，捂脸
> 以后会尝试加入选项以手动指定缓存路径

因为打包的时候只能把所有的文件安装到系统目录，不能直接安装到用户目录

嘛，所以以用户权限运行的时候就没办法去写入了，所以写到用户有权限管理的路径比较合适啦，加入指定路径的命令行选项也是可行的方案。

**Comment by iamapig120** [comment]
> > 唔……打包的话……这里如果不打包 asar 的话……应该是可以正常写入的……
> > 具体不是很了解，捂脸
> > 以后会尝试加入选项以手动指定缓存路径
> 
> 因为打包的时候只能把所有的文件安装到系统目录，不能直接安装到用户目录
> 
> 嘛，所以以用户权限运行的时候就没办法去写入了，所以写到用户有权限管理的路径比较合适啦，加入指定路径的命令行选项也是可行的方案。

收到建议，我个人近期有些忙所以可能无法及时实现相关特性，实在不好意思了……（逃

**Comment by iamapig120** [comment]
/static
缓存路径将会在未来允许修改至其他路径，将会着手实现

**Comment by Yesterday17** [comment]
我先尝试在 typescript 分支下弄一下吧，我现在就在用 manjaro（

**Comment by Yesterday17** [comment]
https://github.com/MajsoulPlus/majsoul-plus/releases/tag/v2.0.0-beta.1
