### ISSUE TITLE
把 node-sass 移动到 devDependencies ？

### ISSUE THREAD

**Issue by rocka** [MajsoulPlus/majsoul-plus#48]
因为所有的 scss 都会被编译成 css，而且运行时并不需要这个东西 ...

另外可以考虑在构建应用时移除所有的 devDependencies，以减少包大小，或者用 webpack 把代码 bundle 一下，只打包有用的部分。

如果实现起来有什么困难我可以帮忙 PR 😂

**Comment by iamapig120** [comment]
欢迎 PR，捂脸（其实应该加到依赖是个意外）（外加现在停电了）
