### ISSUE TITLE
[BUG] 使用window.open()打开新窗口后，如果关闭此窗口，游戏窗口也会崩溃

### ISSUE THREAD

**Issue by kangzq0530** [MajsoulPlus/majsoul-plus#50]
**Bug 描述**
如题

**如何重现**
以下为重现步骤：
1. 进入游戏
2. 打开控制台，输入window.open()+回车
3. 关闭打开的新窗口
4. 提示错误

**预期行为**
打开或关闭新窗口不会影响其他窗口的工作

**截图**
如果您方便的话，可以添加屏幕截图来方便描述您的问题
![image](https://user-images.githubusercontent.com/32447420/54329766-1aa62400-464e-11e9-96c2-79d768654a37.png)

**客户端信息 (请完善以下信息):**
 - 操作系统: [Windows10]
 - 系统架构 [x64]
 - 版本号 [10.0.17134.619]

**备注**
任何有关于这个Bug的其他信息

**Comment by iamapig120** [comment]
请问雀魂 Plus 浏览器版本号是？
可以在关于页面看到

**Comment by iamapig120** [comment]
已在 1.11.1 复现
尝试找到原因中

**Comment by molingyu** [comment]
请不要使用 window.open 
如有需要可以考虑 https://electronjs.org/docs/api/web-contents#event-new-window

更多信息可参阅：
electron/electron#645

**Comment by iamapig120** [comment]
请在使用 window.open 时提供参数
如果在提供参数后仍未解决，请回复并reopen这个issue
