### ISSUE TITLE
[feature request] 插件开发调试，无法import require的问题

### ISSUE THREAD

**Issue by lshy1993** [MajsoulPlus/majsoul-plus#51]
**您是在使用中遇到了什么问题导致的您提交功能建议么？如果是，请描述您遇到的问题**
1.开发插件时，多个js模块文件，如用es6语法进行export和import，无法正常运行。
2.是否能够require node.js的os等库，便于进行截图保存，牌谱文本导出等？
3.是否能够进行重新加载脚本调试，而不是每次重新打开浏览器？

**备注**
如果已经能够完成上述功能，希望能提供开发手册

**Comment by molingyu** [comment]
你需要的是阅读 electron 的开发文档 相信能解决你的疑惑

https://electronjs.org/

**Comment by iamapig120** [comment]
1. 关于插件，现在执行方式是直接插入脚本到页面内，为了保证本地资源的安全目前是禁用了
export 和 import 语句的……十分抱歉。但您可以临时使用 数组 替代 entry 的字符串来使用，数组内的所有 js 文件会自动拼接到一个更长的 js （同一作用域）然后执行。

2. require node.js 的 os 等库，这个会在未来尝试加入的，毕竟没有这些开发起来真的很麻烦。

3. 是否能够进行重新加载脚本调试，而不是每次重新打开浏览器？目前有 Ctrl+R 快捷键可以快速刷新页面。关于保存后直接重新加载……可能不太容易实现，

**Comment by iamapig120** [comment]
> 你需要的是阅读 electron 的开发文档 相信能解决你的疑惑
> 
> https://electronjs.org/

只有 工具 。才是完全使用 electron BrowserWindow API 的……

**Comment by iamapig120** [comment]
https://github.com/MajsoulPlus/majsoul-plus/commit/f78218b274d9055b3c3f879f20c17de03a12e0f1
在 v1.12.x 版本开始后，您可以声明权限并使用 require 语句来调用 node 模块了
