### ISSUE TITLE
[BUG] 桌布生成工具生成的mod在重启后会自动取消勾选

### ISSUE THREAD

**Issue by Kastino** [MajsoulPlus/majsoul-plus#52]
**Bug 描述**
版本：v1.11.1
现象：使用桌布生成工具生成的桌布mod在重新启动雀魂Plus后会自动取消勾选

**如何重现**
以下为重现步骤：
1. 使用桌布生成工具生成mod
2. 勾选启用
3. 启动游戏
4. 重启游戏
5. 自动取消勾选

**预期行为**
预期行为应该和其他自制mod一样保持勾选状态

**暂用解决方案**
1. 把自动生成的mod拷贝出来
2. 在雀魂Plus中删除mod
3. 粘贴回mod文件夹

**客户端信息 (请完善以下信息):**
 - 操作系统: [Windows]
 - 系统架构 [x64]
 - 版本号 [v1.11.1]

**Comment by iamapig120** [comment]
收到，会尝试重现

**Comment by yg110120** [comment]
我的问题是桌布制作工具做出来的新桌布 启动模组后在游戏里不显示 是什么问题。。

**Comment by iamapig120** [comment]
> 我的问题是桌布制作工具做出来的新桌布 启动模组后在游戏里不显示 是什么问题。。

您在进入游戏后请尝试将桌布换为默认桌布再试一次

**Comment by yg110120** [comment]
> 后请尝试将桌布换为默认桌布再试一次

启动自制桌布后会自动替换成雀魂春节活动的那张限时桌布  不管换哪个桌布结果都是一样的

**Comment by iamapig120** [comment]
> > 后请尝试将桌布换为默认桌布再试一次
> 
> 启动自制桌布后会自动替换成雀魂春节活动的那张限时桌布 不管换哪个桌布结果都是一样的 之后重启游戏自制桌布也会自动取消勾选

雀魂春节活动的那张限时桌布是您在游戏中选中了，请您在游戏中取消使用这个桌布

**Comment by yg110120** [comment]
> > > 后请尝试将桌布换为默认桌布再试一次
> > 
> > 
> > 启动自制桌布后会自动替换成雀魂春节活动的那张限时桌布 不管换哪个桌布结果都是一样的 之后重启游戏自制桌布也会自动取消勾选
> 
> 雀魂春节活动的那张限时桌布是您在游戏中选中了，请您在游戏中取消使用这个桌布

是的 我已经取消换成了其他桌布 但是只要我选了自定义桌布 就会自动换成春节这张

**Comment by yg110120** [comment]
> > > 后请尝试将桌布换为默认桌布再试一次
> > 
> > 
> > 启动自制桌布后会自动替换成雀魂春节活动的那张限时桌布 不管换哪个桌布结果都是一样的 之后重启游戏自制桌布也会自动取消勾选
> 
> 雀魂春节活动的那张限时桌布是您在游戏中选中了，请您在游戏中取消使用这个桌布

找到了原因 是其他的插件引起的 但是自定义桌布 在我关掉这个插件后 还是无效果 现在只是不在进游戏的时候强制选中春节桌布了。。我也用了其他人做的桌布也是没有效果

**Comment by yg110120** [comment]
> > > 后请尝试将桌布换为默认桌布再试一次
> > 
> > 
> > 启动自制桌布后会自动替换成雀魂春节活动的那张限时桌布 不管换哪个桌布结果都是一样的 之后重启游戏自制桌布也会自动取消勾选
> 
> 雀魂春节活动的那张限时桌布是您在游戏中选中了，请您在游戏中取消使用这个桌布


自带的桌布工具 针对不同用户登陆会失效  测试QQ登陆有效  直接登陆无效 该怎样解决呢

**Comment by yg110120** [comment]
> > > 后请尝试将桌布换为默认桌布再试一次
> > 
> > 
> > 启动自制桌布后会自动替换成雀魂春节活动的那张限时桌布 不管换哪个桌布结果都是一样的 之后重启游戏自制桌布也会自动取消勾选
> 
> 雀魂春节活动的那张限时桌布是您在游戏中选中了，请您在游戏中取消使用这个桌布

自带的桌布制作工具只会针对一个ID无效  新申请的其他ID都是有效果的  我该怎样解决?

**Comment by iamapig120** [comment]
无法复现，如果您仍遇到相同问题，请重新提出issue
