### ISSUE TITLE
[feature request] 可以建立贴吧宣传雀魂Plus吗？

### ISSUE THREAD

**Issue by Kastino** [MajsoulPlus/majsoul-plus#53]
在亲身使用过后，我觉得这是一个很好的平台，它可以极大的方便mod作者，我希望把这个工具推广开来。如果可能的话，我希望能够开发出安卓版本以方便手机用户。作为建立雀魂Plus吧的人，我承诺会把所以损害官方利益的mod贴全部删除，以期让这个游戏更好。希望您能给我提供一个贴吧头像（因为注意到了您在最下面写的软件图标不遵循上述协议...），并且能制作一个完整的mod制作教程。祝好。

**Comment by iamapig120** [comment]
安卓版本几乎是不会出的……因为完全不会……有关于图像，严格来说一般是只要不用于盈利目的，并注明来源是OK的（CC-BY-NC）

建议贴吧这方面不建议，但是如果您有意建立贴吧并维护也不反对。只是对于贴吧这部分各种原因不太方便参与。（逃走）

以上仅代表我的意见……其余几位开发者意见的话就不太清楚了……
