### ISSUE TITLE
[feature request] proxy設定

### ISSUE THREAD

**Issue by yuuarsi** [MajsoulPlus/majsoul-plus#54]
可否額外增加proxy設定的功能，就是和系統代理分開

**Comment by iamapig120** [comment]
收到建议，目前雀P因为本身其实就是类似于中间人攻击的方式实现的资源替换，所以可能实现有一定难度。
但一定会尝试实现的，毕竟手动指定代理是浏览器标配功能嘛，笑

**Comment by iamapig120** [comment]
预期将在暑假期间完成

**Comment by iamapig120** [comment]
准备开始尝试重写资源获取相关逻辑

**Comment by Yesterday17** [comment]
https://github.com/MajsoulPlus/majsoul-plus/releases/tag/v2.0.0-beta.1
