### ISSUE TITLE
[BUG] 不能保存用户数据

### ISSUE THREAD

**Issue by ywtdzh** [MajsoulPlus/majsoul-plus#58]
**Bug 描述**
关闭窗口之后再打开就需要重新登录，设置也都变成了默认设置

**预期行为**
前几天还都是可以正常保存用户数据的

**客户端信息 (请完善以下信息):**
 - 操作系统: Windows 7 64bit
 - 系统架构 x64
 - 版本号 1.11.1

**Comment by iamapig120** [comment]
请您检查您的 8087 端口是否被占用了，当您的 8087 端口被占用，常导致用户数据丢失的问题

**Comment by ywtdzh** [comment]
> 
> 
> 请您检查您的 8087 端口是否被占用了，当您的 8087 端口被占用，常导致用户数据丢失的问题

我看了一下并没有程序占用8087端口，并且我关闭了一些占用常见端口的服务状况也没有发生变化。重启之后问题暂时没有继续出现，如果出现我会继续跟踪这个issue。
