### ISSUE TITLE
[feature request] 添加移动端支持

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [MajsoulPlus/majsoul-plus#63]
如题，希望添加移动端支持，个人目前有两种假想：

- Electron 移动端打包（？）
- 允许使用桌面版 雀魂 Plus 作为代理服务器，然后对移动端设备的请求进行 MitM

**Comment by Yesterday17** [comment]
前者不可能，但后者在 `2.x` 已经可以用了，效果如图：

![image](https://user-images.githubusercontent.com/8667822/61259913-cdc68b80-a7ae-11e9-9f27-8e9ddfb2a2b5.png)

不过登录的跳转问题有点麻烦。现在的策略是注入用户登录信息，操作方法如下：

1. 在 electron 上登录一次
1. 最大化/最小化 electron 窗口一次（这是现在保存信息的事件，之后可能会修改）
1. 重启一遍雀魂 Plus

嘛，有空我再改改（

**Comment by Yesterday17** [comment]
https://github.com/MajsoulPlus/majsoul-plus/releases/tag/v2.0.0-beta.1
