### ISSUE TITLE
Windows 10和Mac版首页无法打开

### ISSUE THREAD

**Issue by Kimi-Arthur** [MajsoulPlus/majsoul-plus#66]
似乎雀魂更新以后，Plus就无法正确打开首页。

现象：

1. 如果正在别处对战（并关闭），打开Plus可以正常进入对局。
2. 直接打开Plus，首页出现，音乐语音正常，但是首页只能载入部分（无法正常退出）。如图：![Screenshot](https://raw.githubusercontent.com/Kimi-Arthur/images/master/Screenshot%202019-04-25%20at%2016.40.21.png)

**Comment by iamapig120** [comment]
建议您尝试先关闭全部插件和模组再次尝试，如果问题他仍然发生，请按下
Ctrl+I
打开控制台，复制您的报错信息并回复

**Comment by xurz97** [comment]
把报菜名的功能关了就好了

**Comment by iamapig120** [comment]
旧版本自带的报菜名插件与新版雀魂不兼容，请您关闭报菜名插件
