### ISSUE TITLE
Support for EN Server

### ISSUE THREAD

**Issue by gachaponpwn** [MajsoulPlus/majsoul-plus#67]
https://mahjongsoul.game.yo-star.com/

Hi, can you support EN server?

**Comment by iamapig120** [comment]
Received.
We already have plans about EN & JP servers.

**Comment by iamapig120** [comment]
In these days. we tried do this. A good news and a bad one.
We will support EN server next month, but most old mods will not work in new version.

**Comment by Yesterday17** [comment]
https://github.com/MajsoulPlus/majsoul-plus/releases/tag/v2.0.0-beta.1
