### ISSUE TITLE
[BUG] 雀魂plus的logo之后黑屏无响应，控制台code.js报错

### ISSUE THREAD

**Issue by LYSSION** [MajsoulPlus/majsoul-plus#69]
**Bug 描述**
清晰和简练地介绍 BUG 内容

**如何重现**
以下为重现步骤：
1. 访问 '...'
2. 点击 '....'
3. 滚动到 '....'
4. 提示错误
![QQ截图20190525201004](https://user-images.githubusercontent.com/4082025/58369228-032ac780-7f2a-11e9-8955-51fb1fc3ae6e.png)
![QQ截图20190525200941](https://user-images.githubusercontent.com/4082025/58369231-0cb42f80-7f2a-11e9-81ab-c0800ee16b12.png)

**预期行为**
一段清楚且简练的描述说明您预期的行为

**截图**
如果您方便的话，可以添加屏幕截图来方便描述您的问题

**客户端信息 (请完善以下信息):**
 - 操作系统: [e.g. Windows]
 - 系统架构 [e.g. ia32, x64]
 - 版本号 [e.g. v1.5.0]

**备注**
任何有关于这个Bug的其他信息

**Comment by iamapig120** [comment]
请尝试在 关于 页面中 清空缓存再次尝试

**Comment by molingyu** [comment]
看起来像是给本地缓存的 那个codejs 错误了

**Comment by LYSSION** [comment]
关于 页面中 清空缓存后已解决，感谢帮助  :D
