### ISSUE TITLE
进入界面后卡顿无法操作然后黑屏

### ISSUE THREAD

**Issue by Kriitot** [MajsoulPlus/majsoul-plus#70]
我是用的是windows x64的v1.11.1版启动进入后画面卡住无法操作，然后就黑屏了不知道是什么问题网络连接良好，在firefox可以正常play，至于为什么不用v1.11.2，因为使用了各种下载途径均在中途下载失败，怀疑此文件无法正常下载

**Comment by iamapig120** [comment]
该问题源于老版本自带的报菜名插件不兼容最新版雀魂所致
这个问题已经在该版本修复 https://github.com/MajsoulPlus/majsoul-plus/releases/tag/v1.12.0-beta.4
请使用不低于该版本的雀魂Plus进行游戏

**Comment by Kriitot** [comment]
我试了下载您说的这个版本以及其他好多版本，但是都是下载速度极慢（小于10k每秒）而且下到一半多就失败了

**Comment by iamapig120** [comment]
> 我试了下载您说的这个版本以及其他好多版本，但是都是下载速度极慢（小于10k每秒）而且下到一半多就失败了

建议您尝试使用梯子或者科学上网工具等进行下载，Github在境内访问确实不稳定

**Comment by Kriitot** [comment]
谢谢，我马上尝试

**Comment by Kriitot** [comment]
已成功下载使用，感激您的耐心指导，期待推出修改BGM等更强大的功能，加油
