### ISSUE TITLE
没办法用桌布mod了？

### ISSUE THREAD

**Issue by guardianaa** [MajsoulPlus/majsoul-plus#71]
试了 v2.0.0-alpha.1和v1.12.0-beta.4版
只要使用桌布mod，就无法进入游戏，显示 **连接状况不太好，请检查网络代理设置**
不使用就能正常进游戏

**Comment by iamapig120** [comment]
已收到，会在25号之后尝试复现
实在不好意思……期末事情有些多……

**Comment by guardianaa** [comment]
> 已收到，会在25号之后尝试复现
> 实在不好意思……期末事情有些多……

今天又好了，不知道什么原因。。难道真是网络问题
