### ISSUE TITLE
[BUG] 点击启动游戏后窗口变为黑屏无反应

### ISSUE THREAD

**Issue by klklkklkklkkl** [MajsoulPlus/majsoul-plus#73]
**Bug 描述**
点击启动游戏后窗口变为黑屏无反应，无法进入游戏（已删除所有插件）

**截图**

**客户端信息 (请完善以下信息):**
 - 操作系统: [e.g. Windows]
 - 系统架构 [e.g. ia32, x64]
 - 版本号 [v1.12.1]

**备注**
任何有关于这个Bug的其他信息

**Comment by Yesterday17** [comment]
请尝试 `Ctrl+I`（打开开发者工具） 并给出截图。

另外可以尝试一下最新的 [v2.0.0.beta.2](https://github.com/MajsoulPlus/majsoul-plus/releases/tag/v2.0.0-beta.2) 版本。

**Comment by Duuang** [comment]
> 请尝试 `Ctrl+I`（打开开发者工具） 并给出截图。
> 
> 另外可以尝试一下最新的 [v2.0.0.beta.2](https://github.com/MajsoulPlus/majsoul-plus/releases/tag/v2.0.0-beta.2) 版本。

同样问题，win10系统，最新稳定版1.21.1启动游戏之后黑屏
换到2.0.0beta2版本之后问题解决，但是有的原先稳定版本里面能导入的插件到了beta版本不知道为啥导入不进去 
如图，只有仨插件导入成功了
<img width="579" alt="搜狗截图20190816200143" src="https://user-images.githubusercontent.com/31753449/63166346-b6561900-c060-11e9-8f70-56c48ac05dbb.png">

**Comment by Yesterday17** [comment]
旧版模组插件新版不兼容，部分有更新到新版可以进群找。

**Comment by Duuang** [comment]
> 旧版模组插件新版不兼容，部分有更新到新版可以进群找。

好的好的，多谢
