### ISSUE TITLE
[BUG] 请问beta版日服怎么用推特登录？

### ISSUE THREAD

**Issue by l1157737600** [MajsoulPlus/majsoul-plus#75]
点推特登录图标没反应嗄

**Comment by Yesterday17** [comment]
Ctrl+I 看一下控制台（
不过一般都是网络原因

**Comment by Yesterday17** [comment]
![image](https://user-images.githubusercontent.com/8667822/63296141-f6d3c200-c300-11e9-8854-d0d93528799a.png)
![image](https://user-images.githubusercontent.com/8667822/63296146-f9ceb280-c300-11e9-94b6-700a560dca79.png)
![image](https://user-images.githubusercontent.com/8667822/63296149-fb987600-c300-11e9-823e-c31610b36564.png)
测试环境下运行正常,估计是网络原因.
