### ISSUE TITLE
[BUG] 1.11/1.12无法进入游戏

### ISSUE THREAD

**Issue by yumeplus** [MajsoulPlus/majsoul-plus#76]
**Bug 描述**
进入游戏后只出现一串HTML代码。

**如何重现**
以下为重现步骤：
打开雀P后点击进入游戏，无法加载，一直黑屏不动，鼠标点选的时候出现一串HTML代码。
清除缓存或者重新打开缓存工具后问题无解。

**截图**
![无标题.png](https://i.loli.net/2019/08/18/JmeCFXQwyc6bpS3.png)

**客户端信息 (请完善以下信息):**
 - 操作系统: Windows 10 / Ubuntu 19.04
 - 系统架构 x86_64
 - 版本号 1.12.1/1.11.2

**备注**
昨天还正常，今天就不行了。

**Comment by msj1423** [comment]
同样问题，开启显示雀魂PLUS之后一直黑屏无响应

**Comment by Yesterday17** [comment]
雀魂官方更换了游戏域名,并且将原来的域名设置了一层跳转,跳转到新的域名.
群里有发暂时的解决方案(插件),即自己跳转过去,但插件和模组都无法使用.
如果装插件的和可以用开发者工具手动输入 `window.location.href='https://www.majsoul.com/1/'` 进行跳转(但每次运行都要输入一次)

2.0.0-beta.4 修复了这个问题

**Comment by yumeplus** [comment]
> 雀魂官方更换了游戏域名,并且将原来的域名设置了一层跳转,跳转到新的域名.
> 群里有发暂时的解决方案(插件),即自己跳转过去,但插件和模组都无法使用.
> 如果装插件的和可以用开发者工具手动输入 `window.location.href='https://www.majsoul.com/1/'` 进行跳转(但每次运行都要输入一次)
> 
> 2.0.0-beta.4 修复了这个问题

好的，另外考虑过给1.11或1.12修复这个问题吗。

**Comment by Yesterday17** [comment]
[1.x fix.zip](https://github.com/MajsoulPlus/majsoul-plus/files/3513112/1.x.fix.zip)

对 1.x , 把 `zip` 里的文件爱你覆盖 `本体目录/resources/app` 下的文件应该就可以了

**Comment by Yesterday17** [comment]
如果还有问题的话再 reopen 这个 issue，rua
