### ISSUE TITLE
[feature request] 添加跳过结算动画的办法

### ISSUE THREAD

**Issue by monororo** [MajsoulPlus/majsoul-plus#82]
雀魂的结算动画非常漫长，并不是所有人都想看它一点一点跳完的，比如我
请求添加一个能跳过结算动画的办法
我有一个比较简单可行的想法就是在快捷键里添加刷新功能，按键后刷新网页，变相跳过结算动画

**Comment by Yesterday17** [comment]
跳过结算动画可以通过扩展的方式实现，简单思路就是替换掉原有弹出结算界面的函数。

至于刷新，现在已经有刷新页面的方法了（Ctrl+R?具体记不大清楚，可以按 Alt 键在菜单里找）
