### ISSUE TITLE
请问2.X后的资源包不支持正则表达式了吗？

### ISSUE THREAD

**Issue by AlleriaWindy** [MajsoulPlus/majsoul-plus#90]
我尝试修改自带绿头鸭例子中的“resourcepack.json”文件中的replace字段如下：
```
    "replace": [
    {
      "from": "/audio/sound/yiji/lobby_normal[0-9]+\\.mp3",
      "to": "audio/quack.mp3"
    },
    "extendRes/charactor/yiji/.+\\.png"
  ]
```
其中qianzhi文件夹已经改名为yiji，我确定路径正确，然而打开游戏并没有变化，请问是我写错了还是其不支持正则了？

**Comment by Yesterday17** [comment]
是...现在确实不支持正则

**Comment by AlleriaWindy** [comment]
@Yesterday17 感谢你在新年的回复，提问时忘了祝各位开发者新年快乐！
然后还有个问题，wiki上写Ctrl+I能呼出开发者工具，我试了没反应，请问是否当前版本也未支持？

**Comment by Yesterday17** [comment]
@AlleriaWindy 如果我没记错的话现在是 Ctrl+Shift+I 了(

**Comment by AlleriaWindy** [comment]
Oh yeah, it works!!  
支持这种开源、开放的项目，期望将来功能和文档越来越完善~
