### ISSUE TITLE
[BUG] 无法连接到全局服务器

### ISSUE THREAD

**Issue by rishubil** [MajsoulPlus/majsoul-plus#93]
**Bug 描述**
您今天不能以新更新的版本0.8.9.w连接到全局服务器。
当您开始游戏时，仅显示黑屏。

**如何重现**
以下为重现步骤：
1.将“Server to play”值设置为2
2.单击“Launch Game”。
3.仅显示黑屏。

**预期行为**
出现加载屏幕，您应该已连接到主页。

**截图**

![2020-06-09 21 37 31](https://user-images.githubusercontent.com/382014/84148392-e3fdca00-aa99-11ea-8987-cff7bf5a5556.png)

**客户端信息 (请完善以下信息):**
 - 操作系统: Windows 10 Pro 2004(19041.264) Korean
 - 系统架构: x64 
 - 版本号: 2.0.0-beta.8

**备注**
任何有关于这个Bug的其他信息

打开并检查开发人员工具时，出现以下错误：

![2020-06-09 21 38 14](https://user-images.githubusercontent.com/382014/84148416-ee1fc880-aa99-11ea-8204-71548086a2f7.png)

如果您检查实际加载的code.js文件，则结尾字符串似乎丢失。

![2020-06-09 21 38 23](https://user-images.githubusercontent.com/382014/84148430-f37d1300-aa99-11ea-96e7-908e31bb2c38.png)

我希望能成为参考。
（我的中文说得不好，所以我用翻译。请理解。）

**Comment by Yesterday17** [comment]
English is also ok :)

The latest commit should have fixed the problem. A new release will come soon.

**Comment by rishubil** [comment]
I just built the last commit and tested it. It works normally now.

I'll close this issue. Thank you!
