### ISSUE TITLE
[BUG] 缔结契约语音未解锁

### ISSUE THREAD

**Issue by Miuzarte** [MajsoulPlus/majsoul-plus#96]
**Bug 描述**
如图，缔结契约语音未解锁

**如何重现**
寮舍-查看-语音-划到最下

**预期行为**

**截图**
![G JK$M`DV{2(HEBHJ60P$CD](https://user-images.githubusercontent.com/66856838/84557979-ef831680-ad61-11ea-81ac-ffdd53145fe3.png)

**客户端信息 (请完善以下信息):**
 - 操作系统  Windows10 2004
 - 系统架构 x64
 - 版本号 v2.0.0

**备注**

**Comment by iamapig120** [comment]
已在 145e718a039fcdb9027332d15d6c9a2d2198e717 提交中修复，请等待近期新版雀P上线

**Comment by iamapig120** [comment]
您可以在 https://github.com/MajsoulPlus/majsoul-plus/releases/tag/v2.0.1 尝试使用了
